services:
 
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: for-testing
    volumes:
      - ./sqlserver_data/data:/var/opt/mssql/data
      - ./sqlserver_data/log:/var/opt/mssql/log
      - ./sqlserver_data/secrets:/var/opt/mssql/secrets
    ports:
        - 1433:1433
